### ISSUE TITLE
Clean up the Readme

### ISSUE THREAD

**Issue by Carrigan** [smashingboxes/fraqture#25]
Our readme has a couple of broken images and could be more descriptive and helpful.

**Comment by dkniffin** [comment]
Maybe we could also list out the command line options available for each sketch?

**Comment by Carrigan** [comment]
That sounds great. If there was a way to automate that using the cli-options functions that would be even better :smile:

**Comment by dkniffin** [comment]
:100: yea. something like smarfdoc, but for cli-options :grinning:

**Comment by Carrigan** [comment]
We've added a ton since this was opened - I'm closing this out to help the noise.
