### ISSUE TITLE
Write a script that will use a camera to put a picture in /images

### ISSUE THREAD

**Issue by Carrigan** [smashingboxes/fraqture#47]
As a jumping off point for adding live content, we can first find some way to utilize our current infrastructure by having a module in Clojure that can take a picture and place it in the images folder or have Clojure call out into a script in some other language that does so.

**Comment by TylerRockwell** [comment]
This feature has been added and is pending code review.

**Comment by TylerRockwell** [comment]
Feature has now been merged into master.
