### ISSUE TITLE
Minor improvements on shifting-grid

### ISSUE THREAD

**Issue by Carrigan** [smashingboxes/fraqture#56]
Three minor improvements for shifting grid:
- Remove pink outlines
- Slow it down
- Add a delay to the end

**Comment by Carrigan** [comment]
@dkniffin Andy reviewed our current cycle yesterday and came up with recommendations to make everything more uniform. Do you think you can knock this out this week?

**Comment by dkniffin** [comment]
Yea, I should be able to take care of these. What do you mean by "pink outlines"? I don't think I remember seeing those before.

**Comment by Carrigan** [comment]
There is a pink stroke on this drawing when it is part of the cycle sometimes. I think it may be coming from `tweetreader`'s pink stroke not being cleared. I will fix this in the cycle drawing by explicitly clearing the fill and stroke when loading a new drawing.
